apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume-app3
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume-app3
        configMap:
          name: configmap-app3
---
apiVersion: v1
kind: Service
metadata:
  name: service-app3
spec:
  selector:
    app: app3
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app3
spec:
  rules:
  - host: app3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-app3
            port:
              number: 8080
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-app3
            port:
              number: 8080