Vagrant.configure("2") do |config|
  config.vm.define "mbelbiadS" do |server|
    server.vm.box = "generic/alpine318"
    server.vm.hostname = "mbelbiadS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder "./confs", "/vagrant/confs", type: "virtualbox"   
    server.vm.provider "virtualbox" do |vb|
      vb.name = "mbelbiadS"
      vb.cpus = "1"
      vb.memory = "1024"
    end

    server.vm.provision "shell", path: "./scripts/server_script.sh"
  end
end
