
Vagrant.configure("2") do |config|
  config.vm.define "mbelbiadS" do |server|
    config.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "mbelbiadS"
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "mbelbiadS"
      vb.cpus = "3"
      vb.memory = "6024"
    end
    
    server.vm.provision "shell", path: "./scripts/gitlab_install.sh"  
  end
end
