all:
	./scripts/setup.sh

re: clean
	./scripts/setup.sh
clean:
	./scripts/clean.sh
	./scripts/fclean.sh
launch:
	./scripts/launch.sh

re_launch: 
	./scripts/clean.sh
	./scripts/launch.sh

clean_launch:
	./scripts/clean.sh

argo:
	./scripts/argo.sh

push:
	./scripts/push.sh